apiVersion: v1  # Specifies the version of the Kubernetes API you're using
kind: Service  # Defines this as a Service object
metadata:
  name: rentzone  # The name of the service
  namespace: rentzone  # The Kubernetes namespace in which this service exists
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb  # Specifies the type of AWS load balancer to use (Network Load Balancer)
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"  # Indicates that the load balancer is internet-facing
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"  # Enables cross-zone load balancing
spec:
  type: LoadBalancer  # Specifies that this service will be exposed via a Load Balancer
  ports:
    - name: web  # Name of the port
      port: 80  # Port number through which the service is exposed
  selector:
    app: rentzone  # Selector to find which pods to route traffic to, based on labels
